{% set name = "locust" %}
{% set version = "1.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ea6c9c2154252ad2d4a252e7ef6a16d90d97ce24fd6dc135a4a893f769604b6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - locust = locust.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - configargparse >=1.0
    - flask >=1.1.2
    - flask-basicauth >=0.2.0
    - gevent >=20.9.0
    - geventhttpclient >=1.4.4
    - msgpack-python >=0.6.2
    - psutil >=5.6.7
    - python >=3.6
    - pyzmq >=16.0.2
    - requests >=2.9.1
    - werkzeug >=1.0.1

{% set skips = [
  "from_relative_path",
  "no_content_length_streaming",
  "skip_logging"
] %}
test:
  requires:
    - coverage
    - cryptography
    - mock
    - pip
    - pyquery
    - pytest
    - pytest-cov
  imports:
    - locust
  commands:
    - python -m pip check
    - locust --version
    - locust --help
    - pytest --pyargs locust --cov locust -vv -k "not ({{ " or ".join(skips) }})" --cov-fail-under 82

about:
  home: https://locust.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Website load testing framework
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.
  doc_url: https://docs.locust.io
  dev_url: https://github.com/locustio/locust
  doc_source_url: https://github.com/locustio/locust/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
