{% set name = "locustio" %}
{% set version = "0.999" %}

package:
  name: locust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0de762aec06c16f47339d781939a1015f74cf126ee58930b784072c465ab0783

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - locust = locust.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - configargparse >=1.0
    - flask >=0.10.1
    - flask-basicauth >=0.2.0
    - gevent >=1.5.0
    - geventhttpclient
    - msgpack-python >=0.6.2
    - python >=3.6
    - pyzmq >=16.0.2
    - requests >=2.9.1
    - six >=1.10.0
    - psutil >=5.6.7

test:
  requires:
    - mock
    - coverage
    - pytest
    - pytest-cov
    - pyquery
  imports:
    - locust
  commands:
    - locust --version
    - locust --help
    - pytest --pyargs locust --cov locust -k "not from_relative_path and not no_content_length_streaming"

about:
  home: https://locust.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Website load testing framework
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.
  doc_url: https://docs.locust.io
  dev_url: https://github.com/locustio/locust
  doc_source_url: https://github.com/locustio/locust/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
