{% set name = "locust" %}
{% set version = "2.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b351146bbb66ecb5ef83253e01a00affc5be383a1de89a4eed93d08cbf581ff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - locust = locust.main:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - configargparse >=1.0
    - flask >=2
    - flask-basicauth >=0.2.0
    - flask-cors >=3.0.10
    - gevent >=20.9.0
    - geventhttpclient >=1.5.1
    - msgpack-python >=0.6.2
    - psutil >=5.6.7
    - python >=3.6
    - pyzmq >=22.2.1
    - requests >=2.23.0
    - roundrobin >=0.0.2
    - typing-extensions >=3.7.4.3
    - werkzeug >=2.0.0

{% set skips = [
  "autostart_w_load_shape",
  "custom_arguments",
  "custom_exit_code",
  "default_headless_spawn_options_with_shape",
  "from_relative_path",
  "headless_spawn_options_wo_run_time",
  "no_content_length_streaming",
  "skip_logging",
  "web_options",
  "webserver",
] %}
test:
  requires:
    - coverage
    - cryptography
    - mock
    - pip
    - pyquery
    - pytest
    - pytest-cov
    - retry
  imports:
    - locust
  commands:
    - python -m pip check
    - python -c "import locust; assert locust.__version__ == '{{ PKG_VERSION }}'"
    - pip list | grep -E "locust\s*{{ PKG_VERSION | replace('.', '\.') }}"  # [unix]
    - locust --version
    - locust --help
    - pytest --pyargs locust --cov locust -vv -k "not ({{ " or ".join(skips) }})" --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 81

about:
  home: https://locust.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Website load testing framework
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.
  doc_url: https://docs.locust.io
  dev_url: https://github.com/locustio/locust
  doc_source_url: https://github.com/locustio/locust/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
