{% set name = "locustio" %}
{% set version = "0.14.0" %}

package:
  name: locust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dadbe0d2b44c52bdff634a869df4dac1e777567f14d4ce4b6a8b1f78591bf711

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - locust = locust.main:main

requirements:
  host:
    - python
    - pip
  run:
    - configargparse
    - flask >=0.10.1
    - gevent >=1.2.2
    - geventhttpclient
    - msgpack-python >=0.4.2
    - python
    - pyzmq >=16.0.2
    - requests >=2.9.1
    - six >=1.10.0

test:
  requires:
    - mock
    - coverage
    - pytest
    - pytest-cov
  imports:
    - locust
  commands:
    - locust --version
    - locust --help
    - pytest --pyargs locust --cov locust -k "not from_relative_path and not no_content_length_streaming"

about:
  home: https://locust.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Website load testing framework'
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.
  doc_url: https://docs.locust.io
  dev_url: https://github.com/locustio/locust
  doc_source_url: https://github.com/locustio/locust/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
