{% set version = "2.32.1" %}

package:
  name: locust
  version: {{ version }}

source:
  url: https://github.com/locustio/locust/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4fc522f9be7284e573df9dbe252f3ae2cfe4bd31e89dcf1bacbd7793d6732185

build:
  noarch: python
  number: 0
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
    - SKIP_PRE_BUILD=true
  script:
    - rm package.json || del package.json
    - cd locust/webui
    - yarn
    - yarn build
    - cd ../..
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  entry_points:
    - locust = locust.main:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - python >=3.9
    - yarn <2
  run:
    - configargparse >=1.5.5
    - flask >=2.0.0
    - flask-cors >=3.0.10
    - flask-login >=0.6.3
    - gevent >=22.10.2
    - geventhttpclient >=2.3.1
    - msgpack-python >=1.0.0
    - psutil >=5.9.1
    - python >=3.9
    - pywin32-on-windows
    - pyzmq >=25.0.0
    # - requests >=2.26.0
    # upstream tightens this only for py>3.11... not worth breaking noarch
    - requests >=2.32.2
    - tomli >=1.1.0
    - typing_extensions >=4.6.0
    - werkzeug >=2.0.0

test:
  requires:
    - pip
    # https://github.com/locustio/locust/blob/master/tox.ini
    - cryptography
    - mock
    - pyquery
    - retry
    # extras
    - pytest-timeout
    - m2-grep  # [win]
  source_files:
    - locust/test
  imports:
    - locust
  commands:
    - pip check
    - locust --version
    - locust --help
    - python -c "import locust; assert locust.__version__ == '{{ PKG_VERSION }}'"
    - pip list | grep -iE "^locust\s*{{ PKG_VERSION | replace('.', '\.') }}$"
    - locust --version | grep -iE "{{ version.replace('.', '\.') }}"
about:
  home: https://locust.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Website load testing framework
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.
  doc_url: https://docs.locust.io
  dev_url: https://github.com/locustio/locust
  doc_source_url: https://github.com/locustio/locust/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
