{% set version = "2.23.0" %}

package:
  name: locust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/locust/locust-{{ version }}.tar.gz
  sha256: f4857bc0a30578724274d7f1ef5c50c3953735718b31019993c40d5797dbddce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - locust = locust.main:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.2
    - wheel
  run:
    - configargparse >=1.5.5
    - flask >=2.0.0
    - flask-cors >=3.0.10
    - flask-login >=0.6.3
    - gevent >=22.10.2
    - geventhttpclient >=2.0.11
    - msgpack-python >=1.0.0
    - psutil >=5.9.1
    - python >=3.8
    - pywin32-on-windows
    - pyzmq >=25.0.0
    - requests >=2.26.0
    - roundrobin >=0.0.2
    - werkzeug >=2.0.0

test:
  {% set skips = [
    "autostart_w_load_shape",
    "custom_arguments",
    "custom_exit_code",
    "default_headless_spawn_options_with_shape",
    "from_relative_path",
    "headless_spawn_options_wo_run_time",
    "no_content_length_streaming",
    "skip_logging",
    "web_options",
    "webserver",
  ] %}

  # added on https://github.com/conda-forge/locust-feedstock/pull/82
  {% set skips = skips + [
    "autostart_mutliple_locustfiles_with_shape",
    "graceful_exit_when_keyboard_interrupt",
    "percentile_parameter",
    "run_autostart_with_multiple_locustfiles",
    "run_with_userclass_picker",
    "worker_indexes",
  ] %}

  # added on https://github.com/conda-forge/locust-feedstock/pull/83
  {% set skips = skips + [
    "autostart_w_run_time",
    "autostart_wo_run_time",
    "run_headless_with_multiple_locustfiles",
  ] %}

  # added on https://github.com/conda-forge/locust-feedstock/pull/87
  {% set skips = skips + [
    "workers_shut_down_if_master_is_gone",
  ] %}
  # added on https://github.com/conda-forge/locust-feedstock/pull/88
  {% set skips = skips + [
    "processes_ctrl_c",
    "processes_workers_quit_unexpected"
  ] %}
  # added on https://github.com/conda-forge/locust-feedstock/pull/90
  {% set skips = skips + [
    "client_recv",
    "client_send",
  ] %}

  requires:
    - pip
    # https://github.com/locustio/locust/blob/master/tox.ini
    - cryptography
    - mock
    - pyquery
    - retry
    # extras
    - pytest-timeout
  imports:
    - locust
  commands:
    - pip check
    - python -c "import locust; assert locust.__version__ == '{{ PKG_VERSION }}'"
    - pip list | grep -E "locust\s*{{ PKG_VERSION | replace('.', '\.') }}"  # [unix]
    - locust --version
    - locust --help
    # make empty test fixture folder
    - python -c '__import__("pathlib").Path("locust/test").mkdir(parents=True)'
    - pytest -vv --color=yes --tb=long --pyargs locust -k "not ({{ " or ".join(skips) }})" --timeout=300
about:
  home: https://locust.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Website load testing framework
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.
  doc_url: https://docs.locust.io
  dev_url: https://github.com/locustio/locust
  doc_source_url: https://github.com/locustio/locust/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
