# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.32.8

package:
  name: locust
  version: ${{ version }}

source:
  url: https://github.com/locustio/locust/archive/refs/tags/${{ version }}.tar.gz
  sha256: fbac2eb51647c4a89ea75a511bbc1234377f8681f57552541e8f294c54e60e82

build:
  number: 0
  noarch: python
  script:
    env:
      POETRY_DYNAMIC_VERSIONING_BYPASS: ${{ version }}
      SKIP_PRE_BUILD: "true"
    content:
      - rm package.json || del package.json
      - cd locust/webui
      - yarn
      - yarn build
      - cd ../..
      - ${{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - locust = locust.main:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0,<2.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - python ${{ python_min }}.*
    - yarn <2
  run:
    - configargparse >=1.5.5
    - flask >=2.0.0
    - flask-cors >=3.0.10
    - flask-login >=0.6.3
    - gevent >=22.10.2
    - geventhttpclient >=2.3.1
    - msgpack-python >=1.0.0
    - psutil >=5.9.1
    - python >=${{ python_min }}
    - pywin32-on-windows
    - pyzmq >=25.0.0
    # - requests >=2.26.0
    # upstream tightens this only for py>3.11... not worth breaking noarch
    - requests >=2.32.2
    - tomli >=1.1.0
    - typing_extensions >=4.6.0
    - werkzeug >=2.0.0

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - locust
  - files:
      recipe:
        - run_test.py
      source:
        - locust/test/
    requirements:
      run:
        - cryptography
        - mock
        - pyquery
        - pytest-timeout
        - python ${{ python_min }}.*
        - retry
        - if: win
          then:
            - m2-grep
    script:
      - locust --version
      - locust --help
      - python -c "import locust; assert locust.__version__ == '${{ version }}'"
      - pip list | grep -iE "^locust\s*${{ version | replace('.', '\\.') }}$"
      - locust --version | grep -iE "${{ version | replace('.', '\\.') }}"

about:
  license: MIT
  license_file: LICENSE
  summary: Website load testing framework
  homepage: https://locust.io
  repository: https://github.com/locustio/locust
  documentation: https://docs.locust.io
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
