# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.33.0"

package:
  name: locust
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/locust/locust-${{ version }}.tar.gz
    sha256: ba291b7ab2349cc2db540adb8888bc93feb89ea4e4e10d80b935e5065091e8e9
    target_directory: dist
  - url: https://github.com/locustio/locust/archive/refs/tags/${{ version }}.tar.gz
    sha256: 96fca6c750c29fa272a4f6f37ef9be7884a7dbadc78d9e6b3b49a6eaa9b4fe22
    target_directory: src

build:
  number: 0
  noarch: python

  script:
    env:
      SKIP_PRE_BUILD: 'true'
    content:
      - cd dist
      - rm uv.lock || del uv.lock
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - locust = locust.main:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - configargparse >=1.5.5
    - flask >=2.0.0
    - flask-cors >=3.0.10
    - flask-login >=0.6.3
    - gevent >=24.10.1
    - geventhttpclient >=2.3.1
    - msgpack-python >=1.0.0
    - psutil >=5.9.1
    - python >=${{ python_min }}
    - pywin32-on-windows
    - pyzmq >=25.0.0
    - requests >=2.32.2
    - tomli >=1.1.0
    - typing_extensions >=4.6.0
    - werkzeug >=2.0.0

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: locust
  - files:
      recipe:
        - run_test.py
      source:
        - src/locust/test/
    requirements:
      run:
        - cryptography
        - mock
        - pip
        - pyquery
        - pytest-timeout
        - python ${{ python_min }}.*
        - retry
        - if: win
          then:
            - m2-grep
    script:
      - locust --version
      - locust --help
      - python -c "import locust; assert locust.__version__ == '${{ version }}'"
      - pip list | grep -iE "^locust\s*${{ version | replace('.', '\\.') }}$"
      - locust --version | grep -iE "${{ version | replace('.', '\\.') }}"
      - python run_test.py

about:
  license: MIT
  license_file: dist/LICENSE
  summary: Website load testing framework
  homepage: https://locust.io
  repository: https://github.com/locustio/locust
  documentation: https://docs.locust.io
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
