# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.42.4"
  python_check_max: "3.14"
  locust_cloud_min: "1.29.0"
  pytest_min: "8.3.3"
  pytest_max: "10"

recipe:
  name: locust-split
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/locust/locust-${{ version }}.tar.gz
    sha256: b97ab0bbee37bf8108816b5cc4c5312f0aa221c8b91e1ff3a459008833a38396
    target_directory: dist
  - url: https://github.com/locustio/locust/archive/refs/tags/${{ version }}.tar.gz
    sha256: 0621948e0d8a66114936fec8013655f64d8b6c8db9bb5ea793534162b7589be0
    target_directory: src

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: locust
    build:
      number: 0
      script:
        env:
          SKIP_PRE_BUILD: 'true'
          LOCUST_CLOUD_MIN: ${{ locust_cloud_min }}
        content:
          - ${{ PYTHON }} ${{ RECIPE_DIR }}/patch-locust-cloud.py
          - cd dist
          - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - locust = locust.main:main
    requirements:
      host:
        - hatch-vcs
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - configargparse >=1.7.1
        - flask >=2.0.0
        - flask-cors >=3.0.10
        - flask-login >=0.6.3
        - gevent >=24.10.1,<26.0.0,!=25.8.1
        - geventhttpclient >=2.3.1
        - msgpack-python >=1.0.0
        - psutil >=5.9.1
        - pytest >=${{ pytest_min }},<${{ pytest_max }}
        - python >=${{ python_min }}
        - python-socketio >=5.13.0
        - pywin32-on-windows
        - pyzmq >=25.0.0
        - requests >=2.32.2,<2.32.5
        - tomli >=1.1.0
        - typing_extensions >=4.6.0
        - werkzeug >=2.0.0
      run_constraints:
        - locust-cloud >=${{ locust_cloud_min }}
        # optional dependencies with pins: could be optional outputs
        # [mqtt]
        - paho-mqtt >=2.1.0
        # [milvus]
        - pymilvus >=2.5.0
        # [dns]
        - dnspython >=2.8.0
        # [otel]
        - opentelemetry-sdk >=1.38.0
        - opentelemetry-exporter-otlp-proto-grpc >=1.38.0
        - opentelemetry-exporter-otlp-proto-http >=1.38.0
        - opentelemetry-instrumentation-requests >=0.59b0
        - opentelemetry-instrumentation-urllib3 >=0.59b0

    tests:
      - python:
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
          imports: locust

  - package:
      name: locust-with-all
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("locust", exact=True) }}
    tests:
      - files:
          recipe:
            - run_test.py
          source:
            - src/locust/test/
        requirements:
          run:
            - cryptography
            - mock
            - pip
            - pyquery
            - pytest ${{ pytest_min }}.*
            - pytest-timeout
            - python ${{ python_min }}.*
            - retry
        script:
          - locust --version
          - locust --help
          - python run_test.py

about:
  license: MIT
  license_file: dist/LICENSE
  summary: Website load testing framework
  homepage: https://locust.io
  repository: https://github.com/locustio/locust
  documentation: https://docs.locust.io
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.

extra:
  feedstock name: locust
  recipe-maintainers:
    - carlodri
    - bollwyvl
