# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.42.0"
  # revisit after https://github.com/locustio/locust/pull/3236
  # python_check_max: "3.14"
  python_check_max: "3.13"
  locust_cloud_min: "1.27.2"
  pytest_min: "8.3.3"
  pytest_max: "9.0.0"

package:
  name: locust
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/locust/locust-${{ version }}.tar.gz
    sha256: b327c613469bd4508ac5fb398e7fce6f2346985e27463db29a6045beefd5f78b
    target_directory: dist
  - url: https://github.com/locustio/locust/archive/refs/tags/${{ version }}.tar.gz
    sha256: 92ff71b1ed8aa052f1549ec7bde32cd20f4ace1a22339955822b6ab1f25743e7
    target_directory: src

build:
  number: 0
  noarch: python

  script:
    env:
      SKIP_PRE_BUILD: 'true'
      LOCUST_CLOUD_MIN: ${{ locust_cloud_min }}
    content:
      - ${{ PYTHON }} ${{ RECIPE_DIR }}/patch-locust-cloud.py
      - cd dist
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - locust = locust.main:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - configargparse >=1.7.1
    - flask >=2.0.0
    - flask-cors >=3.0.10
    - flask-login >=0.6.3
    - gevent >=24.10.1,<25.8.1
    - geventhttpclient >=2.3.1
    - msgpack-python >=1.0.0
    - psutil >=5.9.1
    - pytest >=${{ pytest_min }},<${{ pytest_max }}
    - python >=${{ python_min }}
    - python-socketio >=5.13.0
    - pywin32-on-windows
    - pyzmq >=25.0.0
    - requests >=2.32.2
    - setuptools >=70.0.0
    - tomli >=1.1.0
    - typing_extensions >=4.6.0
    - werkzeug >=2.0.0
  run_constraints:
    - locust-cloud >=${{ locust_cloud_min }}
    # optional dependencies with pins: could be optional outputs
    - paho-mqtt >=2.1.0
    - psycopg >=3.2.1
    - pymilvus >=2.5.0
    - pymongo >=4.8.0

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
      imports: locust
  - files:
      recipe:
        - run_test.py
      source:
        - src/locust/test/
    requirements:
      run:
        - cryptography
        - mock
        - pip
        - pyquery
        - pytest ${{ pytest_min }}.*
        - pytest-timeout
        - python ${{ python_min }}.*
        - retry
        - if: win
          then:
            - m2-grep
    script:
      - locust --version
      - locust --help
      - python -c "import locust; assert locust.__version__ == '${{ version }}'"
      - pip list | grep -iE "^locust\s*${{ version | replace('.', '\\.') }}$"
      - locust --version | grep -iE "${{ version | replace('.', '\\.') }}"
      - python run_test.py

about:
  license: MIT
  license_file: dist/LICENSE
  summary: Website load testing framework
  homepage: https://locust.io
  repository: https://github.com/locustio/locust
  documentation: https://docs.locust.io
  description: |
    Locust is an easy-to-use, distributed, user load testing tool. It is
    intended for load-testing web sites (or other systems) and figuring out how
    many concurrent users a system can handle.

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
